## Iterasi pada Numpy Array 1D

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

In [3]:
for x in arr:
    print(x)

1
2
3


## Iterasi pada Numpy Array 2D

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


## Iterasi pada Numpy Array 2D

In [16]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [17]:
arr.ndim

3

In [18]:
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Iterasi Dengan nditer()

In [24]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])

In [26]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterasi dengan ndenumerate() pada Array 1D

In [27]:
arr = np.array([1, 2, 3])

In [28]:
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


## Iterasi dengan ndenumerate() pada Array 1D

In [29]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])

In [30]:
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
(0, 3, 0) 10
(0, 3, 1) 11
(0, 3, 2) 12


## Join terhadap 2 Array 1D

In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

In [33]:
arr = np.concatenate((arr1, arr2))

In [34]:
arr

array([1, 2, 3, 1, 2, 3])

## Join terhadap 2 Array 1D

In [37]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [38]:
arr = np.concatenate((arr1, arr2))

In [39]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
arr.shape, arr.ndim

((4, 3), 2)

In [41]:
arr = np.concatenate((arr1, arr2), axis=1)

In [42]:
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [43]:
arr.shape, arr.ndim

((2, 6), 2)

## Stack Terhadap 2 Array 1D

In [44]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

In [48]:
# By default vertikal
arr = np.stack((arr1, arr2))

In [46]:
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [47]:
arr.shape

(2, 3)

## Stack 2 Array 1D Dengan hstack()

In [52]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [50]:
arr = np.hstack((arr1, arr2))

In [51]:
print(arr)

[1 2 3 1 2 3]


## Stack 2 Array 1D Dengan vstack()

In [53]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [55]:
arr = np.vstack((arr1, arr2))

In [56]:
print(arr)

[[1 2 3]
 [4 5 6]]


## Split Terhadap Array 1D

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [63]:
arr = np.array_split(arr, 4)

In [65]:
# Array-nya akan dibagi menjadi 4 bagian
arr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

## Split Terhadap Array 1D

In [66]:
arr = np.array([[7, 8, 9], [10, 11, 12]])

In [76]:
arr = np.array_split(arr, 3)

In [77]:
arr

[array([[array([array([array([array([[7, 8, 9]]), array([[10, 11, 12]])], dtype=object),
                       array([array([], shape=(0, 3), dtype=int64)], dtype=object)],
                      dtype=object)                                                     ],
               dtype=object)                                                              ,
         array([array([array([array([], shape=(0, 3), dtype=int64)], dtype=object)],
                      dtype=object)                                                 ],
               dtype=object)                                                          ,
         array([], dtype=object)]], dtype=object),
 array([[array([], dtype=object), array([], dtype=object),
         array([], dtype=object)]], dtype=object),
 array([], shape=(0, 3), dtype=object)]

## Search pada Array 1D

In [78]:
arr = np.array([1, 2, 3, 4, 5, 4, 4, 5])

In [79]:
x = np.where(arr == 4)

In [80]:
x

(array([3, 5, 6]),)

In [83]:
x = np.where(arr**2 == 4)

In [84]:
x

(array([1]),)

## Sort Pada Array 1D

In [85]:
arr = np.array([2, 3, 0, 1])

In [86]:
np.sort(arr)

array([0, 1, 2, 3])

In [87]:
arr = np.array(['pisang', 'apel', 'melon'])

In [88]:
np.sort(arr)

array(['apel', 'melon', 'pisang'], dtype='<U6')

## Sort Pada Array 2D

In [89]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

In [90]:
np.sort(arr)

array([[2, 3, 4],
       [0, 1, 5]])