## Mendapatkan Nilai Integer Secara Random

In [2]:
from numpy import random

In [9]:
x = random.randint(100)

In [10]:
x

85

## Mendapatkan Nilai Float Secara Random

In [12]:
x = random.rand(100)

In [13]:
x

array([0.93315078, 0.93905528, 0.52272672, 0.88593657, 0.42729187,
       0.06495536, 0.79637039, 0.85548936, 0.30227281, 0.18172116,
       0.73240857, 0.84073497, 0.94246198, 0.9176035 , 0.01183332,
       0.14278457, 0.6921284 , 0.89105393, 0.87843754, 0.81556759,
       0.58094451, 0.36873314, 0.22655502, 0.5682501 , 0.56268711,
       0.87121491, 0.23314034, 0.83057355, 0.69158339, 0.82093173,
       0.89933629, 0.29043115, 0.5202835 , 0.67781055, 0.33268258,
       0.39696624, 0.3370382 , 0.54634465, 0.42988916, 0.8689849 ,
       0.47695931, 0.61186019, 0.37277807, 0.09877965, 0.07944964,
       0.47591546, 0.83736588, 0.70977575, 0.93545305, 0.52776451,
       0.91237811, 0.76339636, 0.81492773, 0.05854543, 0.40947712,
       0.85481581, 0.95751605, 0.40941674, 0.11208557, 0.52219561,
       0.54598566, 0.3099493 , 0.27558769, 0.29350029, 0.49098348,
       0.26570199, 0.58289457, 0.11702958, 0.79306965, 0.07283001,
       0.26251984, 0.91532813, 0.57849154, 0.00678261, 0.25246

In [14]:
x = random.rand()

In [15]:
x

0.5846894942495294

## Membuat Array nD Dengan Nilai Integer Secara Random

In [17]:
# 1 Dimensi
x = random.randint(100, size=(5))

In [18]:
x

array([23, 75, 51, 73, 54])

In [19]:
# 2 Dimensi
x = random.randint(100, size=(3, 5))

In [20]:
x

array([[95, 47, 54, 74, 88],
       [ 4, 93, 19, 47, 22],
       [72, 53, 97, 12,  8]])

In [22]:
# 3 Dimensi
x = random.randint(100, size=(3, 5, 4))

In [23]:
x

array([[[27, 22, 37, 41],
        [ 1, 53, 13, 11],
        [15,  6, 31, 14],
        [16,  5, 47, 14],
        [91, 66, 69, 25]],

       [[ 5, 50, 24, 96],
        [41, 40, 88, 38],
        [86, 56, 63, 42],
        [94, 79, 40, 95],
        [43, 80, 30, 59]],

       [[ 3, 77, 55, 52],
        [31, 98, 55, 73],
        [82, 14, 62, 31],
        [10, 83, 60, 20],
        [43, 40, 33, 88]]])

## Membuat Array nD Dengan Nilai FLoat Secara Random

In [26]:
# 1D
x = random.rand(5)

In [25]:
x

array([0.97850081, 0.62451905, 0.38637172, 0.56244002, 0.3749933 ])

In [30]:
# 2D
x = random.rand(3, 5)

In [28]:
x

array([[0.15747905, 0.44230947, 0.53475435, 0.52227705, 0.18456245],
       [0.97181604, 0.36759399, 0.42926897, 0.95489375, 0.52052068],
       [0.28144263, 0.7368391 , 0.18112346, 0.19780686, 0.7059483 ]])

In [32]:
# 3D
x = random.rand(3, 5, 6)

In [33]:
x

array([[[0.07308532, 0.83447564, 0.66061433, 0.04834194, 0.53707277,
         0.33172957],
        [0.88464764, 0.26882276, 0.02344909, 0.04662152, 0.47976168,
         0.57234094],
        [0.7576718 , 0.80134468, 0.4078705 , 0.51949087, 0.09526527,
         0.52846098],
        [0.00114799, 0.7380646 , 0.12401311, 0.49398422, 0.2231721 ,
         0.3102843 ],
        [0.50740893, 0.44519092, 0.67238977, 0.3050334 , 0.81087166,
         0.92995011]],

       [[0.10467807, 0.91829524, 0.412179  , 0.06303326, 0.62779917,
         0.17001506],
        [0.01823891, 0.06957731, 0.24622313, 0.8556813 , 0.98847141,
         0.49762986],
        [0.78942228, 0.67193215, 0.54722699, 0.84927729, 0.332005  ,
         0.68315777],
        [0.66489018, 0.51485204, 0.00683648, 0.20589991, 0.2843304 ,
         0.72613944],
        [0.46190688, 0.64592258, 0.29101224, 0.43043413, 0.89038104,
         0.99554365]],

       [[0.10520911, 0.11934621, 0.90597746, 0.18721936, 0.16204275,
         0.753644

In [34]:
x.ndim

3

## Membuat Nilai Integer Random dari Array 1D

In [35]:
x = random.choice([3, 5, 7, 9])

In [36]:
x

7

## Mengacak Nilai yang Ada Pada Array 1D

In [37]:
import numpy as np

In [39]:
arr = np.array([1, 2, 3, 4, 5])

In [40]:
random.shuffle(arr)

In [41]:
arr

array([4, 3, 1, 2, 5])