## Mendapatkan Shape dari Array

In [1]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [4]:
arr.shape

(2, 4)

In [5]:
arr.size

8

In [7]:
# Jumlah dimensi
arr.ndim

2

## Mendefenisikan Dimensi

In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)

In [10]:
arr.shape

(1, 1, 1, 1, 4)

In [11]:
arr.size

4

In [12]:
arr.ndim

5

## Reshape dari 1D ke 2D

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [15]:
arr.shape

(12,)

In [23]:
# Dua dimensi
arr = arr.reshape(3, 4)

In [19]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr.ndim

2

## Reshape dari 1D ke 3D

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [24]:
arr = arr.reshape(2, 3, 2)

In [25]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [26]:
arr.ndim

3

## Menggunakan -1 Pada Proses Reshaping

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
# Otomatis menemukan parameternya jika diisi -1
arr = arr.reshape(2, 2, -1)

In [31]:
arr.shape

(2, 2, 2)

## Melakukan Flattening Pada Array

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [34]:
# Mengunah dimensi menjadi 1
arr = arr.reshape(-1)

In [35]:
arr

array([1, 2, 3, 4, 5, 6])

In [36]:
arr.ndim

1

In [37]:
arr.shape

(6,)

In [42]:
arr = arr.reshape(2, 3)

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr.ndim

2

In [45]:
arr = arr.flatten()

In [46]:
arr

array([1, 2, 3, 4, 5, 6])

In [47]:
arr.ndim

1

## Melakukan Duplikasi Pada Array Menggunakan Copy()

In [48]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

In [49]:
arr[0] = 42

In [53]:
# nilai x tidak berubah
arr[0], x[0]

(42, 1)

## Melakukan Duplikasi Pada Array Menggunakan View

In [54]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

In [55]:
arr[0] = 192

In [56]:
# nilai x ikut berubah
arr[0], x[0]

(192, 192)