In [1]:
import numpy as np

## Membuat Numpy Array

In [7]:
arr = np.array([1, 2, 3, 4, 5])

In [8]:
print(arr)

[1 2 3 4 5]


In [9]:
print(type(arr))

<class 'numpy.ndarray'>


In [11]:
# Python list
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

type(a), type(b)

(list, list)

In [12]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [13]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [14]:
arrayA = np.array(a)
arrayB = np.array(b)

type(arrayA), type(arrayB)

(numpy.ndarray, numpy.ndarray)

In [18]:
arrayA + arrayB

array([ 6,  8, 10, 12])

In [19]:
arrayA * arrayB

array([ 5, 12, 21, 32])

In [21]:
arrayA / arrayB

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

## Membuat Numpy Array 0D

In [23]:
arr = np.array(42)

In [24]:
print(arr)

42


## Membuat Numpy Array 1D

In [25]:
arr = np.array([1, 2, 3, 4, 5])

In [26]:
print(arr)

[1 2 3 4 5]


## Membuat Numpy Array 2D

In [27]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])

In [28]:
print(arr)

[[1 2 3]
 [4 5 6]]


## Membuat Numpy Array 3D

In [29]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
               [[1, 2, 3], [4, 5, 6]]])

In [32]:
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Membuat Numpy Array 0s dan 1s

In [34]:
arr = np.zeros(5)

In [35]:
print(arr)

[0. 0. 0. 0. 0.]


In [36]:
arr = np.zeros((5, 2))

In [37]:
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [38]:
arr = np.ones((7, 7))

In [39]:
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [41]:
arr = np.ones((7, 4, 1))

In [42]:
print(arr)

[[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]]


## Menghapus Array

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [46]:
arr = np.delete(arr, 1, axis=0)

In [47]:
print(arr)

[[1 2 3]
 [7 8 9]]


## Mengakses Elemen Pada Numpy Array 1D

In [48]:
arr = np.array([1, 2, 3, 4])

In [49]:
arr[1]

2

In [50]:
arr[1:4]

array([2, 3, 4])

## Mengakses Elemen Pada Numpy Array 2D

In [52]:
arr = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10]])

In [53]:
print(arr[1, 4])

10


In [56]:
print(arr[0, 4])

5


In [57]:
print(arr[1, -1])

10


In [58]:
print(arr[1, 1:4])

[7 8 9]


## Mengecek Tipe Data Pada Numpy Array

In [60]:
arr = np.array([1, 2, 3, 4])

In [61]:
print(arr.dtype)

int64


In [63]:
arr = np.array([1, 2, 3, 4, 5], dtype='S')

In [64]:
print(arr)

[b'1' b'2' b'3' b'4' b'5']


In [66]:
arr = np.array([1, 2, 3, 4, 5], dtype='I')

In [67]:
print(arr.dtype)

uint32


In [68]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)

In [69]:
print(arr.dtype)

int32


## Mengubah Tipe Data Pada Numpy Array

In [70]:
arr = np.array([1.1, 2.1, 3.1])

In [71]:
arr

array([1.1, 2.1, 3.1])

In [72]:
arr = arr.astype('i')

In [73]:
arr

array([1, 2, 3], dtype=int32)

In [74]:
print(arr.dtype)

int32


## Fungsi Arange

In [85]:
arr = np.arange(10)

In [86]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [87]:
print(type(arr))

<class 'numpy.ndarray'>


In [88]:
arr = np.arange(10, 20)

In [89]:
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [93]:
arr = np.arange(10, 20, 2)

In [94]:
arr

array([10, 12, 14, 16, 18])

In [95]:
arr = np.arange(-1, 1, 0.1)

In [96]:
arr

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])