## Filter Pada Numpy Array 1D

In [1]:
import numpy as np

In [2]:
arr = np.array([41, 42, 43, 44])

In [3]:
x = [True, False, True, False]

In [4]:
arr = arr[x]

In [5]:
arr

array([41, 43])

In [6]:
arr = np.array([41, 42, 43, 44])

In [7]:
filter_arr = arr > 42

In [8]:
arr = arr[filter_arr]

In [9]:
arr

array([43, 44])

## Filter Pada Numpy Array 1D Menggunakan Lebih Dari 1 Kondisi

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
filter_arr = (arr % 2 == 0) & (arr > 2)

In [12]:
arr = arr[filter_arr]

In [13]:
arr

array([4, 6, 8])

## Filter Pada Numpy Array 2D

In [14]:
arr = np.array([['1', 'one'],
                ['2', 'two'],
                ['3', 'three'],
                ['4', 'four'],
                ['5', 'five']])

In [15]:
arr.shape

(5, 2)

In [16]:
filter_arr = np.array(['two', 'four'])

In [18]:
arr = arr[np.in1d(arr[:, 1], filter_arr)]

In [20]:
arr

array([['2', 'two'],
       ['4', 'four']], dtype='<U5')